dirksite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls", namespace="homepage")),
    path("movies/", include("movie_reviews.urls", namespace="movie_reviews")),
]
admin.site.site_header = "Dirk's website Admin Page"
admin.site.site_title = admin.site.site_header
admin.site.index_title = "Dirk's website database tables"

homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    
    path('', views.HomePageView.as_view(), name="home"),
]

movie_reviews/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "movie_reviews"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("add/", views.AddMovieView.as_view(), name="movie-add"),
    path("details/<int:pk>/", views.MovieDetailView.as_view(), name="movie-detail"),
    path(
        "details/<int:pk>/review/add/",
        views.MovieReviewCreateView.as_view(),
        name="review-add",
    ),
    path(
        "reviews/<int:pk>/update/",
        views.MovieReviewUpdateView.as_view(),
        name="review-update",
    ),
    path(
        "reviews/<int:pk>/delete/",
        views.MovieReviewDeleteView.as_view(),
        name="review-delete",
    ),
    path("list/", views.MovieStatusListView.as_view(), name="movie-list"),
    path("download/", views.DownloadIMDbDataView.as_view(), name="imdb-download"),
    path(
        "download/progress/", views.DownloadProgressView.as_view(), name="imdb-convert"
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=firefox">
    <title>{{ title }}</title>
    {% comment %} <link rel="stylesheet" href="style.css"> {% endcomment %}
  </head>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</html>

templates/navbar.html
<nav>
    <ul> 
        <li><a href="{% url 'homepage:home' %}">Home</a></li>
        <li class="dropdown">
            <a href="{% url 'movie_reviews:home' %}" class="dropbtn">Movies</a>
            <ul class="dropdown-content">
                <li><a href="{% url 'movie_reviews:movie-add' %}">Add Movie</a></li>
                <li><a href="{% url 'movie_reviews:movie-list' %}">Movie List</a></li>
            </ul>
        </li> 
    </ul>
</nav>