dirksite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls", namespace="homepage")),
    path("movies/", include("movie_reviews.urls", namespace="movie_reviews")),
]
admin.site.site_header = "Dirk's website Admin Page"
admin.site.site_title = admin.site.site_header
admin.site.index_title = "Dirk's website database tables"

movie_reviews/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "movie_reviews"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("add/", views.AddMovieView.as_view(), name="movie-add"),
    path("details/<int:pk>/", views.MovieDetailView.as_view(), name="movie-detail"),
    path(
        "details/<int:pk>/review/add/",
        views.MovieReviewCreateView.as_view(),
        name="review-add",
    ),
    path(
        "reviews/<int:pk>/update/",
        views.MovieReviewUpdateView.as_view(),
        name="review-update",
    ),
    path(
        "reviews/<int:pk>/delete/",
        views.MovieReviewDeleteView.as_view(),
        name="review-delete",
    ),
    path("list/", views.MovieStatusListView.as_view(), name="movie-list"),
    path("download/", views.DownloadIMDbDataView.as_view(), name="imdb-download"),
    path(
        "download/progress/", views.DownloadProgressView.as_view(), name="imdb-convert"
    ),
]

movie_reviews/models.py
from django.db import models
from django.urls import reverse

CHOICES = {
    "enjoyment": (
        (0.0, "0: dislike"),
        (0.5, "0.5"),
        (1.0, "1: mweh"),
        (1.5, "1.5"),
        (2.0, "2: fun"),
        (2.5, "2.5"),
        (3.0, "3: good / cool"),
        (3.5, "3.5"),
        (4.0, "4: great"),
    ),
    "quality": (
        (0.0, "0: bad, not worth watching"),
        (0.5, "0.5"),
        (1.0, "1: bad, but interesting"),
        (1.5, "1.5"),
        (2.0, "2: good enough"),
        (2.5, "2.5"),
        (3.0, "3: good"),
        (3.5, "3.5"),
        (4.0, "4: great"),
    ),
}


class MovieStatus(models.Model):
    # TODO: figure out if th options can be turned into a class,
    # so they are encapsulated for every field.
    STATUS_UNKNOWN = None
    STATUS_WATCHED = True
    STATUS_NOT_WATCHED = False
    STATUS_CHOICES = (
        (STATUS_UNKNOWN, "unknown"),
        (STATUS_WATCHED, "watched"),
        (STATUS_NOT_WATCHED, "not watched"),
    )
    PRIORITY_YES = True
    PRIORITY_NO = False
    PRIORITY_CHOICES = (
        (PRIORITY_YES, "yes"),
        (PRIORITY_NO, "no"),
    )
    AVAILABILITY_UNKNOWN = None
    AVAILABILITY_AVAILABLE = True
    AVAILABILITY_NOT_AVAILABLE = False
    AVAILABILITY_CHOICES = (
        (AVAILABILITY_UNKNOWN, "unknown"),
        (AVAILABILITY_AVAILABLE, "available"),
        (AVAILABILITY_NOT_AVAILABLE, "not available"),
    )
    tconst = models.CharField(max_length=12, unique=True, null=False)
    status = models.BooleanField(
        default=False, null=True, blank=True, choices=STATUS_CHOICES
    )
    priority = models.BooleanField(
        default=False, null=False, blank=False, choices=PRIORITY_CHOICES
    )
    netflix = models.BooleanField(
        default=None, null=True, blank=True, choices=AVAILABILITY_CHOICES
    )
    prime = models.BooleanField(
        default=None, null=True, blank=True, choices=AVAILABILITY_CHOICES
    )

    def __str__(self):
        return self.tconst

    class Meta:
        verbose_name_plural = "Movie Status"


class MovieReview(models.Model):
    tconst = models.ForeignKey(to=MovieStatus, null=False, on_delete=models.DO_NOTHING)
    watch_date = models.DateField(null=True, blank=True)
    enjoyment = models.DecimalField(
        choices=CHOICES["enjoyment"],
        blank=True,
        null=True,
        max_digits=2,
        decimal_places=1,
    )
    quality = models.DecimalField(
        choices=CHOICES["quality"],
        blank=True,
        null=True,
        max_digits=2,
        decimal_places=1,
    )
    notes = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Movie Reviews"


class MovieDataFiles(models.Model):
    file_name = models.CharField(unique=True, max_length=50, null=False)
    imdb_path = models.URLField(unique=True, null=False)
    output_path = models.URLField(null=False, blank=True)
    last_successful_download = models.DateTimeField(null=True, blank=True)
    progress = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Movie Data Files"

movie_reviews/forms.py
from django import forms
from django.core.exceptions import ValidationError
import re

from .models import MovieReview


class AddMovieForm(forms.Form):
    imdb_id = forms.URLField(label="IMDb URL", required=True)

    def clean_imdb_id(self):
        """
        Get the id from the url.
        """
        url = self.cleaned_data["imdb_id"]
        if "www.imdb.com/" not in url:
            raise ValidationError("URL does not originate from IMDb.com.")
        if not re.compile("/tt[0-9]+").search(url):
            raise ValidationError("URL does not contain the tconst movie id.")
        regex = re.compile("^tt[0-9]+")
        tconst = list(filter(lambda id: regex.match(id), url.split("/")))[0]
        return tconst


class MovieReviewForm(forms.ModelForm):
    watch_date = forms.DateField(
        required=False, widget=forms.DateInput(attrs={"type": "date"})
    )
    notes = forms.CharField(required=False, widget=forms.Textarea(), empty_value=None)

    class Meta:
        model = MovieReview
        exclude = ["tconst"]


class DownloadIMDbForm(forms.Form):
    # title.basics.tsv.gz
    # title.ratings.tsv.gz
    movie_info = forms.BooleanField(label="Basic movie info: ", required=False)
    movie_ratings = forms.BooleanField(label="Movie ratings: ", required=False)

movie_reviews/views.py
from django.contrib import messages
from django.db.models.query import QuerySet
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    FormView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    ListView,
)
from django.views.generic.edit import ModelFormMixin

from movie_reviews.filters import MovieStatusFilter

from .models import MovieStatus, MovieReview, MovieDataFiles
from .forms import AddMovieForm, MovieReviewForm, DownloadIMDbForm


class HomePageView(TemplateView):
    template_name = "movie_reviews/index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["message"] = "Welcome to the Movie Page motherfucker!"
        return context


class AddMovieView(FormView):
    """
    Custom form that takes an imdb url and retrieves the tconst from it.
    """

    template_name = "movie_reviews/movie_add.html"
    form_class = AddMovieForm
    success_url = "/movies/"

    def form_valid(self, form):
        tconst = form.cleaned_data["imdb_id"]

        movie_status, created = MovieStatus.objects.get_or_create(
            tconst=tconst,
            defaults={
                "status": None,
                "priority": False,
                "netflix": None,
                "prime": None,
            },
        )
        self.id = movie_status.id
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("movie_reviews:movie-detail", kwargs={"pk": self.id})


class MovieDetailView(DetailView, ModelFormMixin):
    """
    Details for a movie, defined by the tables MovieStatus and WatchedDates.
    """

    model = MovieStatus
    fields = ["status", "priority", "netflix", "prime"]
    template_name = "movie_reviews/movie_details.html"
    context_object_name = "movie_status"

    def get_success_url(self):
        return self.request.path

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.get_object()
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["movie_status_form"] = self.get_form()
        context["movie_status_object"] = self.get_object()
        watched_dates = MovieReview.objects.filter(
            tconst=context["movie_status_object"]
        ).order_by("watch_date")
        context["movie_reviews"] = watched_dates
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class MovieReviewCreateView(CreateView):
    model = MovieReview
    form_class = MovieReviewForm
    template_name = "movie_reviews/review_add.html"
    context_object_name = "review"

    def get_success_url(self):
        return reverse("movie_reviews:movie-detail", kwargs={"pk": self.kwargs["pk"]})

    def form_valid(self, form):
        movie_status = MovieStatus.objects.get(pk=self.kwargs["pk"])
        form.instance.tconst = movie_status
        messages.success(self.request, "Review added successfully.")
        return super().form_valid(form)


class MovieReviewUpdateView(UpdateView):
    model = MovieReview
    form_class = MovieReviewForm
    template_name = "movie_reviews/review_update.html"

    def get_success_url(self):
        movie_review = MovieReview.objects.get(pk=self.kwargs["pk"])
        movie_id = movie_review.tconst.id
        return reverse("movie_reviews:movie-detail", kwargs={"pk": movie_id})

    def form_valid(self, form):
        messages.success(self.request, "Review changed successfully.")
        return super().form_valid(form)


class MovieReviewDeleteView(DeleteView):
    model = MovieReview
    template_name = "movie_reviews/review_delete.html"
    context_object_name = "movie_review_object"

    def get_success_url(self):
        movie_review = MovieReview.objects.get(pk=self.kwargs["pk"])
        movie_id = movie_review.tconst.id
        return reverse("movie_reviews:movie-detail", kwargs={"pk": movie_id})

    def form_valid(self, form):
        messages.success(self.request, "Review deleted successfully.")
        return super().form_valid(form)


class MovieStatusListView(ListView):
    template_name = "movie_reviews/movie_list.html"
    model = MovieStatus
    context_object_name = "movie_status_list"
    paginate_by = 5
    paginate_orphans = 1

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = MovieStatusFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.filterset.form
        return context


class DownloadIMDbDataView(FormView):
    """
    Shows buttons to download imdb files on command.
    Maybe better to use a async view.
    """

    template_name = "movie_reviews/download_files.html"
    form_class = DownloadIMDbForm
    success_url = "/download/progress/"

    def get_success_url(self):
        return reverse("movie_reviews:imdb-convert")

    def form_valid(self, form):
        movie_info = form.cleaned_data["movie_info"]
        movie_ratings = form.cleaned_data["movie_ratings"]

        print("movie_info: ", movie_info)

        # TODO: download the files simultaniously, like in the pandas project
        # TODO: when a file is downloaded, start converting with pandas and save in database
        # look at tasks.py
        # https://www.youtube.com/playlist?list=PLOLrQ9Pn6cayGytG1fgUPEsUp3Onol8V7
        if movie_ratings:
            movie_ratings_data = MovieDataFiles.objects.get(file_name="imdb_ratings")
            print(movie_ratings_data.imdb_path)

        if movie_info:
            movie_info_data = MovieDataFiles.objects.get(file_name="basic_movie_info")
            print(movie_info_data.imdb_path)

        return super().form_valid(form)


class DownloadProgressView(TemplateView):
    # TODO: make a progress bar, that includes name of stage
    # TODO: create Asynchronous class-based views: https://docs.djangoproject.com/en/5.1/topics/class-based-views/
    template_name = "movie_reviews/download_progress.html"

movie_reviews/templates/movie_reviews/download_files.html
{% extends 'base.html' %}

{% block content %}

<h1>IMDb files to download</h1>

<div>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock%}

movie_reviews/templates/movie_reviews/download_progress.html
{% extends 'base.html' %}

{% block content %}
<h1>files are being downloaded</h1>
progress numbers
{% endblock%}

movie_reviews/templates/movie_reviews/index.html
{% extends 'base.html' %}

{% block content %}
{{ message }}
{% endblock%}

movie_reviews/templates/movie_reviews/movie_add.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add or lookup a movie</h1>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method='post'>
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <br>
        <input type="submit">
    </form>
{% endblock%}

movie_reviews/templates/movie_reviews/movie_details.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ movie_status_object.tconst }}</h1>

{% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </ul>
{% endif %}

<div>
    <h2>Status</h2>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ movie_status_form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
</div>

<div>
    <h2>Info</h2>
    <a id="imdb_web_link" href="https://www.imdb.com/title/{{ movie_status_object.tconst }}/">link to the IMDb movie page</a>
</div>

<div>
    <h2>Reviews</h2>
    <a id=add-review href="{% url 'movie_reviews:review-add' pk=movie_status_object.pk %}" class="btn btn-primary">Add Review</a>
    <table>
        <tr>
            <th>watch date</th>
            <th>enjoyment</th>
            <th>quality</th>
            <th>link</th>
        </tr>
        {% for review in movie_reviews %}
        <tr>
            <td>{{ review.watch_date }}</td>
            <td>{{ review.enjoyment }}</td>
            <td>{{ review.quality }}</td>
            <td><a id="review_link" href="{% url 'movie_reviews:review-update' pk=review.pk %}">edit</a></td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock%}

movie_reviews/templates/movie_reviews/movie_list.html
{% extends 'base.html' %}
{% comment %} Not sure if this works {% endcomment %}
{% block title %}{{ block.super }} | Movie List {% endblock title %}

{% block content %}
<style>
    /* Style the table */
    table {
        {% comment %} width: 100%; {% endcomment %}
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 1em;
        font-family: Arial, sans-serif;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

    /* Style the table header */
    table th {
        background-color: rgb(255, 164, 0);
        color: #ffffff;
        text-align: center;
        padding: 12px 15px;
    }

    /* Style the table rows */
    table td {
        padding: 12px 15px;
        border-bottom: 1px solid #dddddd;
        text-align: center;
    }

    /* Add alternating row colors */
    table tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }

    /* Highlight the last row */
    table tr:last-of-type {
        border-bottom: 2px solid rgb(255, 164, 0);
    }

    /* Style the links */
    table a {
        color: rgb(255, 164, 0);
        text-decoration: none;
    }

    table a:hover {
        text-decoration: underline;
    }
</style>
<body>
    <h1>Movie Status List</h1>
    
    <form method='GET' url="{% url 'movie_reviews:movie-list' %}">
        <table>
        {% for field in form %}
            <tr>
                <td>{{ field.label_tag }}</td>
                {% for f in field %}
                    <td>{{ f }}</td>
                {% endfor %} 
                <td>{{ field.errors }}</td> 
            </tr>
        {% endfor %}
        </table>
        <input type="submit" value="Submit" class="btn btn-primary" />
    </form>

    <table>
        <tr>
            <th>tconst</th>
            <th>priority</th>
            <th>status</th>
            <th>netflix</th>
            <th>prime</th>
            <th>link</th>
        </tr>
        {% for movie in movie_status_list %}
        <tr>
            <td>{{ movie.tconst }}</td>
            <td>{{ movie.get_priority_display }}</td>
            <td>{{ movie.get_status_display }}</td>
            <td>{{ movie.get_netflix_display }}</td>
            <td>{{ movie.get_prime_display }}</td>
            <td><a href="{% url 'movie_reviews:movie-detail' pk=movie.pk %}">details</a></td>
        </tr>
        {% endfor %}
    </table>
    
    <br>
    {% if is_paginated %}
        {% include 'movie_reviews/pagination_nav.html' %}
    {% endif %}
</body>

{% endblock content %}

movie_reviews/templates/movie_reviews/pagination_nav.html
{% comment %} source: https://waynelambert.dev/blog/post/how-to-implement-list-view-pagination-with-django/ {% endcomment %}
{% if is_paginated %}
<style>
    /* Style the pagination container */
    .pagination {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 20px 0;
        font-family: Arial, sans-serif;
    }

    /* Style the step links */
    .step-links a {
        color: #009879;
        padding: 8px 16px;
        text-decoration: none;
        border: 1px solid #ddd;
        margin: 0 4px;
        border-radius: 4px;
        transition: background-color 0.3s, color 0.3s;
    }

    /* Style the current page indicator */
    .step-links .current {
        padding: 8px 16px;
        margin: 0 4px;
        border: 1px solid #009879;
        border-radius: 4px;
        background-color: #009879;
        color: white;
    }

    /* Hover effects for links */
    .step-links a:hover {
        background-color: #ddd;
        color: #009879;
    }
</style>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}

movie_reviews/templates/movie_reviews/review_add.html
{% extends 'base.html' %}

{% block content %}

<h1>New review for movie {{ movie_status_object.tconst }}</h1>

<div>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock%}

movie_reviews/templates/movie_reviews/review_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete review "{{ object.id }}" for movie "{{ object.tconst.tconst }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a href="{% url 'movie_reviews:movie-detail' pk=movie_review_object.tconst.pk %}">Cancel</a>
  </form>
{% endblock %}

movie_reviews/templates/movie_reviews/review_update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Update review</h1>
  <form action='' method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" value="Update">Save changes</button>
  </form>
  <br>
  <br>
  <a href="{% url 'movie_reviews:review-delete' pk=object.pk %}">Delete Review</a>
{% endblock %}